"""removed unique constraint from ComboKey on support_staff table

Revision ID: 69de3c4e5853
Revises: a3c23cdc19fc
Create Date: 2024-10-17 13:30:13.517797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69de3c4e5853'
down_revision = 'a3c23cdc19fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_staff', schema=None) as batch_op:
        batch_op.drop_constraint('uq_support_staff_COMBOKEY', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_staff', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_support_staff_COMBOKEY', ['COMBOKEY'])

    # ### end Alembic commands ###
