"""small change to enrollment model to troubleshoot data not seeding

Revision ID: 89404e4d600e
Revises: a5d5449c63a1
Create Date: 2024-10-16 16:54:24.024926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89404e4d600e'
down_revision = 'a5d5449c63a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_annual_enrollment_NCESSCH', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_enrollment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_annual_enrollment_NCESSCH', ['NCESSCH'])

    # ### end Alembic commands ###
