"""removed unique constraint from objectid in Enrollment model

Revision ID: a3c23cdc19fc
Revises: 89404e4d600e
Create Date: 2024-10-16 17:28:04.435838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c23cdc19fc'
down_revision = '89404e4d600e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_annual_enrollment_OBJECTID', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_enrollment', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_annual_enrollment_OBJECTID', ['OBJECTID'])

    # ### end Alembic commands ###
