"""small update to enrollment model to rename field to align with school model

Revision ID: a5d5449c63a1
Revises: a70a55baa9c4
Create Date: 2024-10-16 16:46:03.610902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d5449c63a1'
down_revision = 'a70a55baa9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NCESSCH', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_annual_enrollment_school_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_annual_enrollment_NCESSCH'), ['NCESSCH'])
        batch_op.drop_constraint('fk_annual_enrollment_school_id_schools', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_annual_enrollment_NCESSCH_schools'), 'schools', ['NCESSCH'], ['NCESSCH'])
        batch_op.drop_column('school_id')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint('uq_schools_OBJECTID', type_='unique')
        batch_op.drop_column('OBJECTID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OBJECTID', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_schools_OBJECTID', ['OBJECTID'])

    with op.batch_alter_table('annual_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_annual_enrollment_NCESSCH_schools'), type_='foreignkey')
        batch_op.create_foreign_key('fk_annual_enrollment_school_id_schools', 'schools', ['school_id'], ['NCESSCH'])
        batch_op.drop_constraint(batch_op.f('uq_annual_enrollment_NCESSCH'), type_='unique')
        batch_op.create_unique_constraint('uq_annual_enrollment_school_id', ['school_id'])
        batch_op.drop_column('NCESSCH')

    # ### end Alembic commands ###
