"""added SavedSchools model

Revision ID: f019d8a6591a
Revises: dbd9168548f4
Create Date: 2024-10-22 16:30:43.572280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f019d8a6591a'
down_revision = 'dbd9168548f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NCESSCH', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NCESSCH'], ['schools.NCESSCH'], name=op.f('fk_saved_schools_NCESSCH_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_schools'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_schools')
    # ### end Alembic commands ###
